"""Regenerate the README's statistics block from the repository itself.

Backs `make readme-stats`. Every figure here is measured at run time, so a number in the
README cannot drift from the thing it describes — the failure this script exists to prevent
is three different test counts in one repo, which discredits every other figure alongside
them.

Rewrites the region between the STATS markers in README.md and exits non-zero if the
markers are missing or if any measurement could not be taken.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
START = "<!-- STATS:START -->"
END = "<!-- STATS:END -->"


def test_count() -> int:
    """Ask pytest, rather than trusting a number typed into prose."""
    proc = subprocess.run(
        [str(REPO / ".venv/bin/python"), "-m", "pytest", "--collect-only", "-q"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=False,
    )
    match = re.search(r"(\d+) tests collected", proc.stdout)
    if not match:
        raise RuntimeError(f"could not parse pytest collection output:\n{proc.stdout[-800:]}")
    return int(match.group(1))


def source_stats() -> tuple[int, int]:
    """(files, lines) of first-party Python under src/."""
    files = sorted(p for p in (REPO / "src").rglob("*.py") if "__pycache__" not in p.parts)
    lines = sum(len(p.read_text(encoding="utf-8").splitlines()) for p in files)
    return len(files), lines


def corpus_stats() -> dict[str, object]:
    sys.path.insert(0, str(REPO))
    from src.config import get_settings
    from src.retrieval.chunker import load_chunks

    settings = get_settings()
    papers = json.loads(settings.metadata_path.read_text())
    chunks = load_chunks(settings.chunks_path, classify_on_load=False)
    return {
        "papers": len(papers),
        "chunks": len(chunks),
        "mean_tokens": sum(c.token_count for c in chunks) / len(chunks),
        "chunks_mb": settings.chunks_path.stat().st_size / 1_048_576,
        "metadata_kb": settings.metadata_path.stat().st_size / 1024,
    }


def index_stats() -> dict[str, object]:
    from src.config import INDEX_NAME, get_settings

    path = get_settings().index_dir / f"{INDEX_NAME}.faiss"
    if not path.exists():
        return {"present": False}
    return {"present": True, "bytes": path.stat().st_size, "mb": path.stat().st_size / 1_048_576}


def render() -> str:
    tests = test_count()
    files, lines = source_stats()
    corpus = corpus_stats()
    index = index_stats()
    today = datetime.now(UTC).strftime("%Y-%m-%d")
    corpus_row = (
        f"| Committed corpus | `chunks_512.json` {corpus['chunks_mb']:.0f} MiB, "
        f"`metadata.json` {corpus['metadata_kb']:.0f} KiB |"
    )

    index_row = (
        f"| Index | FAISS `IndexFlatIP`, {index['bytes']:,} bytes ({index['mb']:.1f} MiB) |"
        if index["present"]
        else "| Index | not built |"
    )

    return f"""{START}
<!-- Generated by `make readme-stats`. Do not edit by hand. -->

| | | Regenerate with |
|---|---|---|
| Tests | {tests}, all passing | `make test` |
| First-party Python | {files} files, {lines:,} lines under `src/` | `make readme-stats` |
| Papers | {corpus["papers"]} (arXiv cs.LG, all published 2026-05-28) | `make corpus-info` |
| Chunks | {corpus["chunks"]:,} at chunk size 512 | `make corpus-info` |
| Mean tokens per chunk | {corpus["mean_tokens"]:.1f} (whitespace tokens) | `make corpus-info` |
| Embedding | `BAAI/bge-large-en`, 1024-dim | — |
{index_row} `make index` |
| Sparse | Okapi BM25 over lowercased whitespace tokens | — |
{corpus_row} `make verify-corpus` |

*Measured {today}.*
{END}"""


def main() -> int:
    readme = REPO / "README.md"
    text = readme.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print(f"README.md is missing the {START} / {END} markers", file=sys.stderr)
        return 1

    block = render()
    updated = re.sub(
        re.escape(START) + r".*?" + re.escape(END), lambda _: block, text, flags=re.DOTALL
    )
    readme.write_text(updated, encoding="utf-8")
    print(block)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
